pipeline {
    agent any

    stages {
        stage('Install & Test') {
            steps {
                sh 'npm ci'
                sh 'npx playwright test'
            }
        }

        stage('Generate Report') {
            steps {
                sh 'npx playwright show-report --output=playwright-report'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'playwright-report/**', fingerprint: true

            emailext (
                to: 'agarwalrajat01@gmail.com',
                subject: "Build #${env.BUILD_NUMBER} - ${currentBuild.currentResult}",
                body: "Check attached test report.\nBuild URL: ${env.BUILD_URL}",
                attachmentsPattern: 'playwright-report/index.html',
                mimeType: 'text/html'
            )
        }
    }
}
